version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "8000:8000"
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=fake
      - AWS_SECRET_ACCESS_KEY=fake
      - S3_BUCKET_NAME=magk-excel-local
      - USE_LOCAL_S3=true
      - USE_LOCAL_CHROME=true
      - LOG_LEVEL=DEBUG
    volumes:
      - .:/app
      - /app/venv  # Exclude venv from volume mount
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack/data
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - localstack_data:/tmp/localstack

volumes:
  localstack_data: